spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false # we use gulp + BrowserSync for livereload

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:mariadb://localhost:3306/PILOT
    url: jdbc:h2:mem:database:service;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

liquibase:
  contexts: h2

logging:
  level:
    ROOT: INFO
    com.chornyi.poc.database: DEBUG

